### PR TITLE
Add support for minify option

### PR DESCRIPTION
**Pull request by mikemartin**
Hey @philicevic! I needed to remove collapsed whitespace in production and it seemed like there was no way to pass the `minify` option to the `html-webpack-plugin`. I've added a `minify` option that defaults to `auto`, which you can set to `false` to disable minification for all environments.

However, it doesn't work and there appears to be a related open issue here: https://github.com/jantimon/html-webpack-plugin/issues/1094

Thoughts?

### CODE REVIEW

**Comment by philicevic** [comment]
Hey @mikemartin !
Sorry for the late answer.
If I am getting it right, I would just require the user to pass an object for the minify option.
For the moment this would prevent the issue you mentioned and it works (at least for me?).

**Comment by mikemartin** [comment]
Thanks @philicevic. Are you saying I just need to pass the minify object in the current release?

**Comment by philicevic** [comment]
Hey, @mikemartin !

I tested this by using your changes. With that you can just pass the minify object like its described in the [documentation of html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin#minification) and that should do the job.

I actually have one question, what does the 'auto' value do as a default? I couldn't find anything about it on the documentation.
But thanks for you work already! :)

**Comment by mikemartin** [comment]
Hey @philicevic
It seems like `auto` is the default that minifys only when in production mode. 
https://github.com/jantimon/html-webpack-plugin/blob/895db297d06e1c31aa89c73969f5f040ba7ef88d/index.js#L116

**Comment by philicevic** [comment]
If I am right, similar to the issue you mentioned before (https://github.com/jantimon/html-webpack-plugin/issues/1094), `auto` is also not supported yet. I guess it will be available with v4 of html-webpack-plugin but it is not in v3.2. Until then i don't see why we should use it.
I think preparing our own default settings would be the better option for now.

**Comment by mikemartin** [comment]
Totally agree 👍

Mike Martin
mike-martin.ca | @mikemartin604 | +61 413 780 407

________________________________

**Pull request merged**
